apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-helm-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  controller: nginx.org/ingress-controlle
  rules:
  - host: cluster.mari1327.pp.ua
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: heml-app-service
            port:
              number: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: heml-app-service
  namespace: dev
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.service.port }}
  selector:
    app: chart-golang-deploy 
  sessionAffinity: None
  type: {{ .Values.service.type }}

