apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    - host: cluster.mari1327.pp.ua
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: helm-app-service
                port:
                  number: {{ .Values.service.port }}
            path: /

