apiVersion: v1
kind: Service
metadata:
  name: heml-app-service
  namespace: dev
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: chart-golang-deploy
  sessionAffinity: None
  type: {{  .Values.service.type }}

  
