apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dev
  namespace: dev
  labels:
    app: my-golang-deploy
    release: beta
spec:
  selector:
    matchLabels:
      project: golang
  template:
    metadata:
      labels:
        project: golang
    spec:
      containers:
        - name: golang-web
          image: docker.io/marina1327/app1-go:dev-2023-11-22-15-35-26 # {"$imagepolicy": "flux-system:podinfo"} #NS+policyinfo
          ports:
            - containerPort: {{ .Values.service.port }}