replicaCount: 2
service:
  name: nginx/nginx-ingress 
  type: LoadBalancer 
  port: 8080
ingress:
  enabled: true
  hosts:
    - host: 34.107.74.43 
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80