---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: dev
spec:
  interval: 3m0s
  path: ./app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
