---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  filterTags:
    pattern: '^dev-(\d+)-*'
    extract: '$1'
  imageRepositoryRef:
    name: podinfo
  policy:
    numerical:
      order: asc
