replicaCount: 2
service:
  name: nginx/nginx-ingress 
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
