replicaCount: 2
image:
  repository: nginx/nginx-ingress
service:
  type: LoadBalancer 
  port: 8080
ingress:
  enabled: true
   annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: 34.107.74.43
      paths:
        - /
service:
  name: service/my-app-service  
  port: 8080  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80


