replicaCount: 2
image:
  repository: nginx/nginx-ingress
service:
  type: LoadBalancer 
  port: 8080
ingress:
  enabled: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80


