apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dev-chart
  namespace: helm
  labels:
    app: chart-golang-deploy
    release: beta
spec:
  selector:
    matchLabels:
      app: chart-golang-deploy  
  template:
    metadata:
      labels:  
        app: chart-golang-deploy
    spec:      
      containers:
        - name: golang-web
          image: docker.io/marina1327/app1-go:dev-2023-11-22-15-35-26 # {"$imagepolicy": "flux-system:podinfo"} #NS+policyinfo
          ports:
            - containerPort: 8080
